# 远程连接配置
listen_addresses = '0.0.0.0'
port = 6793
wal_level = hot_standby
synchronous_commit = on
max_wal_senders = 4
wal_keep_segments = 256
hot_standby = on
max_connections = 1000
wal_log_hints = on
password_encryption = scram-sha-256

# 三个插件：Oracle函数,pg_pathman分区管理扩展，pg_stat_statementsSQL执行统计
shared_preload_libraries = '$libdir/orafce,$libdir/pg_pathman,$libdir/pg_stat_statements,$libdir/pglogical,auth_delay,passwordcheck,pg_statsinfo'
pg_stat_statements.track = all

bgwriter_delay = 10ms
bgwriter_lru_maxpages = 1000
bgwriter_lru_multiplier = 10.0
effective_io_concurrency = 2

commit_delay = 20
commit_siblings = 9

checkpoint_timeout = 30min
checkpoint_completion_target = 0.8
synchronous_commit = on
full_page_writes = on

vacuum_cost_delay = 0
autovacuum = on
autovacuum_naptime = 6s
autovacuum_vacuum_cost_delay = 0

# 备库配置，单机压测的话用不上
update_process_title = off
wal_buffers = -1
wal_writer_delay = 10ms
max_wal_size = 16GB
archive_mode = off
archive_command = ''

idle_in_transaction_session_timeout = 300000
max_parallel_workers_per_gather = 0

# pg_statsinfo,监控插件
pg_statsinfo.repository_keepday = 1
pg_statsinfo.enable_maintenance = 'on'
pg_statsinfo.maintenance_time = '00:02:00'
pg_statsinfo.snapshot_interval = 5min
pg_statsinfo.repolog_keepday = 1
pg_statsinfo.enable_alert = off

# 远程连接
tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 10

# 日志
log_destination = 'csvlog'
logging_collector = on
log_directory = '/home/postgres/log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_truncate_on_rotation = on
log_rotation_age = 1440min
log_rotation_size = 100MB
log_connections = off
log_disconnections = off
log_error_verbosity = verbose
log_line_prefix = '%m %a %d %u %p %r %c %l %i %v %x %e %%'
log_lock_waits = ON
log_statement = 'none'
log_min_error_statement = panic
log_min_messages = error
track_counts = on
track_activities = on
track_functions = pl
log_statement = 'ddl'
log_timezone = 'PRC'

# #####只删去插件######

listen_addresses = '0.0.0.0'
port = 6793
wal_level = hot_standby
synchronous_commit = on
max_wal_senders = 4
wal_keep_segments = 256
hot_standby = on
max_connections = 1000
wal_log_hints = on
password_encryption = scram-sha-256

bgwriter_delay = 10ms
bgwriter_lru_maxpages = 1000
bgwriter_lru_multiplier = 10.0
effective_io_concurrency = 2

commit_delay = 20
commit_siblings = 9

checkpoint_timeout = 30min
checkpoint_completion_target = 0.8
synchronous_commit = on
full_page_writes = on

vacuum_cost_delay = 0
autovacuum = on
autovacuum_naptime = 6s
autovacuum_vacuum_cost_delay = 0

update_process_title = off
wal_buffers = -1
wal_writer_delay = 10ms
max_wal_size = 16GB
archive_mode = off
archive_command = ''

idle_in_transaction_session_timeout = 300000
max_parallel_workers_per_gather = 0

tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 10

log_destination = 'csvlog'
logging_collector = on
log_directory = '/home/postgres/log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_truncate_on_rotation = on
log_rotation_age = 1440min
log_rotation_size = 100MB
log_connections = off
log_disconnections = off
log_error_verbosity = verbose
log_line_prefix = '%m %a %d %u %p %r %c %l %i %v %x %e %%'
log_lock_waits = ON
log_statement = 'none'
log_min_error_statement = panic
log_min_messages = error
track_counts = on
track_activities = on
track_functions = pl
log_statement = 'ddl'
log_timezone = 'PRC'

# #######精简配置#######
port = 6793
max_connections = 1000
shared_buffers = 1GB
effective_cache_size = 8GB
random_page_cost = 1.1

synchronous_commit = offfull_page_writes = off
full_page_writes = off
checkpoint_timeout = 30min
max_wal_size = 4GB

autovacuum = on
bgwriter_delay = 10ms

track_counts = on
track_activities = on
log_min_messages =error
